name: Swift Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-aarch64-linux-gnu

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27

    - name: Download and Install Official Android Swift SDK
      run: |
        curl -fSL -o android.artifactbundle.tar.gz https://download.swift.org/swift-6.0.3-release/android-sdk/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE_android.artifactbundle.tar.gz
        swift sdk install android.artifactbundle.tar.gz

    - name: Build Swift Project
      run: |
        swift build --swift-sdk aarch64-unknown-linux-android24 -c release

    - name: Package Shared Library
      run: |
        mkdir -p distribution/lib/arm64-v8a
        find .build/aarch64-unknown-linux-android24/release -maxdepth 1 -type f -name "*.so" -exec cp {} distribution/lib/arm64-v8a/ \;
        cd distribution && zip -r ../LiveContainerAndroid-libs.zip .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LiveContainer-Android-Binaries
        path: LiveContainerAndroid-libs.zip
