name: Swift Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b

    - name: Install Android Swift SDK
      run: |
        swift experimental-sdk install https://github.com/swift-arm/swift-android-toolchain/releases/download/5.10.1-release/swift-5.10.1-RELEASE-android-aarch64-24-sdk.artifactbundle.tar.gz

    - name: Build Swift Project
      run: |
        swift build --experimental-swift-sdk aarch64-unknown-linux-android24 -c release

    - name: Package Shared Library
      run: |
        mkdir -p distribution/lib/arm64-v8a
        find .build/aarch64-unknown-linux-android24/release -maxdepth 1 -type f -name "*.so" -exec cp {} distribution/lib/arm64-v8a/ \;
        cd distribution && zip -r ../LiveContainerAndroid-libs.zip .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LiveContainer-Android-Binaries
        path: LiveContainerAndroid-libs.zip
